### ISSUE TITLE
Optimization of CSS for Calendar Page

### ISSUE THREAD

**Issue by fmeldrum** [MariAzhdari/finalProject-HubPlanner#114]

**Comment by fmeldrum** [comment]
use class from previous CSS that Eli did 

![Image](https://github.com/MariAzhdari/finalProject-HubPlanner/assets/140701973/a17ce4a8-7eba-4c44-a22f-7f9f3f7fc0f2)

**Comment by MariAzhdari** [comment]
I did it.
