### ISSUE TITLE
Create database for 'users' (volunteers and trainees)

### ISSUE THREAD

**Issue by mickeyhaile2** [MariAzhdari/finalProject-HubPlanner#26]
## Story

- **As a** .............

- **I Want** .............

- **So That** .............

## Acceptance Criteria

1. Given .............
   - When .............
   - Then .............
2. Given .............
   - When .............
   - Then .............

## Implementation Notes

1.
2.

## Checklist:

- [ ] I have defined the user story
- [ ] I have defined some acceptance criteria
- [ ] I have included any implementation notes
- [ ] I have included all relevant links

**Comment by fmeldrum** [comment]
Need to define what was including in the table - agree in Stand up - 30/07

**Comment by fmeldrum** [comment]
Discussed 4th august. 
Agreed that we need 3 x tables - user table, meeting table (for each meeting), attendance table 
Each row of the attendance table will attend a meeting (using date)

**User Table**

-user ID (generated as the row is completed)
- Name
- Role
- Login email
- Encrypted password 
- City

**Meeting Table**

-Meeting ID (generated as row is completed) - _someone will need to maintain this database (MVP) + future can look to fetch from CYF calendar
- Date
- 


**Attendance Table**
- user ID -*foreign key
- Meeting ID *foreign key
- online / in person / not attending

**Comment by fmeldrum** [comment]
Agreed to split the work in the following way:

- @mickeyhaile2 to build the Calendar Table
- @MariAzhdari  to build the User table (as its related to login page)

Then work together on the Attendance Table 

Approach - 
Create database locally and then push to render when ready.

**Comment by fmeldrum** [comment]
'Class Table' is built - Mickey needs support with trying to connect the database with server.js file . Agreed 12/08 meeting at 10am with the group to resolve :)

User table is built and it's connected to login page 

Attendance table is built and is in process of being connected to attendance page - issue being worked on.
